# Generated by Django 4.2 on 2025-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0024_auto_final_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='autoupdate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='update_time',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='linked_files',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='thumb_url',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='autoupdate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='update_time',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
    ]
