# Generated by Django 4.2 on 2025-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0025_deployment_autoupdate_deployment_update_time_and_more'),
    ]

    operations = [
    migrations.AddField(
        model_name='deployment',
        name='country',
        field=models.CharField(blank=True, max_length=100, null=True),
    ),
]
