# Generated by Django 4.2 on 2025-03-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0025_deployment_autoupdate_deployment_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
    ]
