# Generated by Django 4.2 on 2025-03-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0026_auto_20250325_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
    ]
