# Generated by Django 4.2 on 2025-03-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0027_add_missing_fields_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
    ]
