# Generated by Django 4.2 on 2025-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0028_add_audio_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='configuration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sd_card_size',
            field=models.FloatField(blank=True, help_text='Size in GB', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_card_batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_card_icc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
