# Generated by Django 4.2 on 2025-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0029_remove_deployment_password_remove_device_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='device',
            name='coordinate_uncertainty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='country',
        ),
        migrations.RemoveField(
            model_name='device',
            name='gps_device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='habitat',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mic_direction',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mic_height',
        ),
        migrations.RemoveField(
            model_name='device',
            name='protocol_checklist',
        ),
        migrations.RemoveField(
            model_name='device',
            name='score',
        ),
        migrations.RemoveField(
            model_name='device',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user_email',
        ),
    ]
