# Generated by Django 4.2 on 2025-04-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_models', '0030_remove_redundant_device_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='annotators',
            field=models.ManyToManyField(blank=True, null=True, related_name='annotatable_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_device_ID',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.device'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='managed_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='deployments', to='data_models.project'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.site'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='UTC', null=True, use_pytz=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewable_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
