/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapImport } from './routes/map'
import { Route as LoginImport } from './routes/login'
import { Route as CallImport } from './routes/call'
import { Route as IndexImport } from './routes/index'
import { Route as DeploymentsIndexImport } from './routes/deployments/index'
import { Route as DeploymentsDeviceIdIndexImport } from './routes/deployments/$deviceId/index'
import { Route as DeploymentsDeviceIdDataFileIdImport } from './routes/deployments/$deviceId/$dataFileId'

// Create/Update Routes

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CallRoute = CallImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsIndexRoute = DeploymentsIndexImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsDeviceIdIndexRoute = DeploymentsDeviceIdIndexImport.update({
  id: '/deployments/$deviceId/',
  path: '/deployments/$deviceId/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsDeviceIdDataFileIdRoute =
  DeploymentsDeviceIdDataFileIdImport.update({
    id: '/deployments/$deviceId/$dataFileId',
    path: '/deployments/$deviceId/$dataFileId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/deployments/$deviceId/$dataFileId': {
      id: '/deployments/$deviceId/$dataFileId'
      path: '/deployments/$deviceId/$dataFileId'
      fullPath: '/deployments/$deviceId/$dataFileId'
      preLoaderRoute: typeof DeploymentsDeviceIdDataFileIdImport
      parentRoute: typeof rootRoute
    }
    '/deployments/$deviceId/': {
      id: '/deployments/$deviceId/'
      path: '/deployments/$deviceId'
      fullPath: '/deployments/$deviceId'
      preLoaderRoute: typeof DeploymentsDeviceIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/deployments/$deviceId/$dataFileId': typeof DeploymentsDeviceIdDataFileIdRoute
  '/deployments/$deviceId': typeof DeploymentsDeviceIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/deployments/$deviceId/$dataFileId': typeof DeploymentsDeviceIdDataFileIdRoute
  '/deployments/$deviceId': typeof DeploymentsDeviceIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/deployments/$deviceId/$dataFileId': typeof DeploymentsDeviceIdDataFileIdRoute
  '/deployments/$deviceId/': typeof DeploymentsDeviceIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/login'
    | '/map'
    | '/deployments'
    | '/deployments/$deviceId/$dataFileId'
    | '/deployments/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/login'
    | '/map'
    | '/deployments'
    | '/deployments/$deviceId/$dataFileId'
    | '/deployments/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/login'
    | '/map'
    | '/deployments/'
    | '/deployments/$deviceId/$dataFileId'
    | '/deployments/$deviceId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  DeploymentsDeviceIdDataFileIdRoute: typeof DeploymentsDeviceIdDataFileIdRoute
  DeploymentsDeviceIdIndexRoute: typeof DeploymentsDeviceIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  DeploymentsDeviceIdDataFileIdRoute: DeploymentsDeviceIdDataFileIdRoute,
  DeploymentsDeviceIdIndexRoute: DeploymentsDeviceIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/call",
        "/login",
        "/map",
        "/deployments/",
        "/deployments/$deviceId/$dataFileId",
        "/deployments/$deviceId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/call": {
      "filePath": "call.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/deployments/": {
      "filePath": "deployments/index.tsx"
    },
    "/deployments/$deviceId/$dataFileId": {
      "filePath": "deployments/$deviceId/$dataFileId.tsx"
    },
    "/deployments/$deviceId/": {
      "filePath": "deployments/$deviceId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
