/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ObservationsImport } from './routes/observations'
import { Route as MapImport } from './routes/map'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as DeploymentsIndexImport } from './routes/deployments/index'
import { Route as DeploymentsSiteNameIndexImport } from './routes/deployments/$siteName/index'
import { Route as DeploymentsSiteNameDataFileIdImport } from './routes/deployments/$siteName/$dataFileId'
import { Route as DeploymentsSiteNameDataFileIdObservationsImport } from './routes/deployments/$siteName/$dataFileId/observations'

// Create/Update Routes

const ObservationsRoute = ObservationsImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => rootRoute,
} as any)

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsIndexRoute = DeploymentsIndexImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsSiteNameIndexRoute = DeploymentsSiteNameIndexImport.update({
  id: '/deployments/$siteName/',
  path: '/deployments/$siteName/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsSiteNameDataFileIdRoute =
  DeploymentsSiteNameDataFileIdImport.update({
    id: '/deployments/$siteName/$dataFileId',
    path: '/deployments/$siteName/$dataFileId',
    getParentRoute: () => rootRoute,
  } as any)

const DeploymentsSiteNameDataFileIdObservationsRoute =
  DeploymentsSiteNameDataFileIdObservationsImport.update({
    id: '/observations',
    path: '/observations',
    getParentRoute: () => DeploymentsSiteNameDataFileIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/observations': {
      id: '/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof ObservationsImport
      parentRoute: typeof rootRoute
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/deployments/$siteName/$dataFileId': {
      id: '/deployments/$siteName/$dataFileId'
      path: '/deployments/$siteName/$dataFileId'
      fullPath: '/deployments/$siteName/$dataFileId'
      preLoaderRoute: typeof DeploymentsSiteNameDataFileIdImport
      parentRoute: typeof rootRoute
    }
    '/deployments/$siteName/': {
      id: '/deployments/$siteName/'
      path: '/deployments/$siteName'
      fullPath: '/deployments/$siteName'
      preLoaderRoute: typeof DeploymentsSiteNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/deployments/$siteName/$dataFileId/observations': {
      id: '/deployments/$siteName/$dataFileId/observations'
      path: '/observations'
      fullPath: '/deployments/$siteName/$dataFileId/observations'
      preLoaderRoute: typeof DeploymentsSiteNameDataFileIdObservationsImport
      parentRoute: typeof DeploymentsSiteNameDataFileIdImport
    }
  }
}

// Create and export the route tree

interface DeploymentsSiteNameDataFileIdRouteChildren {
  DeploymentsSiteNameDataFileIdObservationsRoute: typeof DeploymentsSiteNameDataFileIdObservationsRoute
}

const DeploymentsSiteNameDataFileIdRouteChildren: DeploymentsSiteNameDataFileIdRouteChildren =
  {
    DeploymentsSiteNameDataFileIdObservationsRoute:
      DeploymentsSiteNameDataFileIdObservationsRoute,
  }

const DeploymentsSiteNameDataFileIdRouteWithChildren =
  DeploymentsSiteNameDataFileIdRoute._addFileChildren(
    DeploymentsSiteNameDataFileIdRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/observations': typeof ObservationsRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/deployments/$siteName/$dataFileId': typeof DeploymentsSiteNameDataFileIdRouteWithChildren
  '/deployments/$siteName': typeof DeploymentsSiteNameIndexRoute
  '/deployments/$siteName/$dataFileId/observations': typeof DeploymentsSiteNameDataFileIdObservationsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/observations': typeof ObservationsRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/deployments/$siteName/$dataFileId': typeof DeploymentsSiteNameDataFileIdRouteWithChildren
  '/deployments/$siteName': typeof DeploymentsSiteNameIndexRoute
  '/deployments/$siteName/$dataFileId/observations': typeof DeploymentsSiteNameDataFileIdObservationsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/observations': typeof ObservationsRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/deployments/$siteName/$dataFileId': typeof DeploymentsSiteNameDataFileIdRouteWithChildren
  '/deployments/$siteName/': typeof DeploymentsSiteNameIndexRoute
  '/deployments/$siteName/$dataFileId/observations': typeof DeploymentsSiteNameDataFileIdObservationsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/map'
    | '/observations'
    | '/deployments'
    | '/deployments/$siteName/$dataFileId'
    | '/deployments/$siteName'
    | '/deployments/$siteName/$dataFileId/observations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/observations'
    | '/deployments'
    | '/deployments/$siteName/$dataFileId'
    | '/deployments/$siteName'
    | '/deployments/$siteName/$dataFileId/observations'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/map'
    | '/observations'
    | '/deployments/'
    | '/deployments/$siteName/$dataFileId'
    | '/deployments/$siteName/'
    | '/deployments/$siteName/$dataFileId/observations'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ObservationsRoute: typeof ObservationsRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  DeploymentsSiteNameDataFileIdRoute: typeof DeploymentsSiteNameDataFileIdRouteWithChildren
  DeploymentsSiteNameIndexRoute: typeof DeploymentsSiteNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ObservationsRoute: ObservationsRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  DeploymentsSiteNameDataFileIdRoute:
    DeploymentsSiteNameDataFileIdRouteWithChildren,
  DeploymentsSiteNameIndexRoute: DeploymentsSiteNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/map",
        "/observations",
        "/deployments/",
        "/deployments/$siteName/$dataFileId",
        "/deployments/$siteName/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/observations": {
      "filePath": "observations.tsx"
    },
    "/deployments/": {
      "filePath": "deployments/index.tsx"
    },
    "/deployments/$siteName/$dataFileId": {
      "filePath": "deployments/$siteName/$dataFileId.tsx",
      "children": [
        "/deployments/$siteName/$dataFileId/observations"
      ]
    },
    "/deployments/$siteName/": {
      "filePath": "deployments/$siteName/index.tsx"
    },
    "/deployments/$siteName/$dataFileId/observations": {
      "filePath": "deployments/$siteName/$dataFileId/observations.tsx",
      "parent": "/deployments/$siteName/$dataFileId"
    }
  }
}
ROUTE_MANIFEST_END */
