site_name: ARISE MDS sensor portal help
nav:
    - Home: "index.md"
    - About: "about.md"
    - Core features: "functions/index.md"
    - Data structure: 
      - Overview: "structure/index.md"
      - Project: "structure/project.md"
      - Device: "structure/device.md"
      - Deployment: "structure/deployment.md"
      - Datafile: "structure/datafile.md"
    - For developers: 
      - Overview: "developers/index.md"
      - Code Reference: "reference/"
    - For admin:
      - Overview: "admin/index.md"
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      default_lang: python
plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings

