site_name: ARISE MDS sensor portal help
nav:
    - Home: "index.md"
    - About: "about.md"
    - Data structure: 
      - Overview: "structure/index.md"
      - Project: "structure/project.md"
      - Device: "structure/device.md"
      - Deployment: "structure/deployment.md"
      - Datafile: "structure/datafile.md"
      - Model detail:
        - Site: structure/detail/site.md
        - DataType: structure/detail/datatype.md
        - Project: structure/detail/project.md
        - DeviceModel: structure/detail/devicemodel.md
        - Device: structure/detail/device.md
        - Deployment: structure/detail/deployment.md
        - DataFile: structure/detail/datafile.md
        - Taxon: structure/detail/taxon.md
        - Observation: structure/detail/observation.md
        - DataPackage: structure/detail/datapackage.md
    - API:
      - Index: api/index.md
      - Examples: api/arise_mds_api_examples.md
      - Upload example: api/upload_data_workflow.md
    - For developers: 
      - Overview: "developers/index.md"
      - Data handlers: "developers/data_handlers.md"
      - Generic jobs: "developers/generic_jobs.md"
      - Code Reference: "reference/"
    - For admin:
      - Overview: "admin/index.md"
      - UVA management: "UVA/UVA.md"
      - Permissions: "admin/permissions.md"
      - Admin only models details: 
        - Project Job: admin/detail/projectjob.md
        - Data Storage input: admin/detail/data_storage_input.md
        - Archive: admin/detail/archive.md
        - TAR file: admin/detail/tarfile.md
theme: 
  name: readthedocs
  features:
    - navigation.indexes
use_directory_urls: True
markdown_extensions:
  - pymdownx.highlight:
      default_lang: python
plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [../sensor_portal]

